@host = http://localhost:3000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJ1c2VyMUBlbWFpbC5jb20iLCJuYW1lIjoidXNlcjEiLCJpc2hvc3QiOjAsImlhdCI6MTY3NDgxOTkyMSwiZXhwIjoxNzA2Mzc3NTIxfQ.oNyuciQCm0z7NOIlGhlREoURzie9gg0aCJWogHsdn5U

### Simple hello world
GET {{host}}/hello-world

### Simple hello world from /api/auth

GET {{host}}/api/auth/hello-world

### Try Login, return token

POST {{host}}/api/auth/login
content-type: application/json

{
    "email": "user1@email.com",
    "password": "123456"
}

### Test Login
GET {{host}}/api/auth/checklogin
Authorization: {{token}}

### New User
POST {{host}}/api/user/
content-type: application/json

{
    "name": "user5",
    "email": "user15@email.com",
    "password": "123456",
    "ishost": false
}

### Edit User
PUT {{host}}/api/user/1
Authorization: {{token}}
content-type: application/json

{
    "name": "user1",
    "email": "user1@email.com",
    "password": "123456",
    "ishost": true
}

### Get All countries
GET {{host}}/api/countries

### Get 1 country
GET {{host}}/api/countries/1

### GET all cities of one country by country id
GET {{host}}/api/countries/1/cities

### New Country
POST {{host}}/api/countries/
content-type: application/json

{
    "name": "United States 22222",
    "capital": "Washington, D.C.",
    "continent": "North America"
}

### Edit Country
PUT {{host}}/api/countries/1
content-type: application/json

{
    "name": "United States 2",
    "capital": "Washington, D.C.",
    "continent": "North America"
}

### Get All cities
GET {{host}}/api/cities

### Get 1 city
GET {{host}}/api/cities/1

### New city
POST {{host}}/api/cities/
content-type: application/json

{
    "name": "Juiz de Fora",
    "country_id": "2"
}

### Edit city
PUT {{host}}/api/cities/16
content-type: application/json

{
    "name": "Juiz de Fora 2",
    "country_id": "1"
}


